name: Django App Workflow

on:
  pull_request:
    branches:
      - main

env:
  DOCKER_IMAGE_NAME: unit_conversion_app
  DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

jobs:
  build_and_test:
    name: Build_and_Test
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: unit_conversion/

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt      

      - name: Linting
        run: |
          flake8 ./webapp

      - name: Run tests
        if: always()
        run: |
          pytest
    

  deploy:
    name: dockerzied deploy
    runs-on: ubuntu-latest
    needs: build_and_test
    defaults:
        run:
          working-directory: unit_conversion/
    steps:
      - name: Build Docker image
        if: always()
        run: |
          docker build -t $DOCKER_IMAGE_NAME .

      - name: Login to Docker Hub
        if: always()
        run: |
          echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin

      - name: Push Docker image
        if: always()
        run: |
          docker push $DOCKER_IMAGE_NAME


  