name: Django App Workflow

on:
  push:
    branches:
      - main


jobs:
  linting_workflow:
    name: Python lint
    uses: RAM797/github-reusable-workflows/.github/workflows/pylint.yml@main
    with:
      path: unit_conversion/webapp
      out: unit_conversion/${{github.run_id}}_lint_results.log


  